# The list of classes that will attempt to destroy remote data after download.
#   Requirements :
#     1. Class code located at ./src/cloners/
#     2. Class name also listed under enabled_cloners config.yaml key
destroy_remote:
  [RedditDataCloner]

# The list of classes that the cloner manager will initialize and run.
#   Requirements :
#     1. Class code located ./src/cloners/
#     2. Class has a run function
enabled_cloners:
  # [GoogleDriveCloner]
  [RedditDataCloner]
